import { uid } from "@/lib/utils";
import { emptyAdvisor, emptyDocs, emptyPerson } from "./empty";
import type { PqData } from "./types";

export const HAMMARTH_PQ: PqData = {
  advisor: "Michael Jensen, CFP®",
  paraPlanner: "A. Nguyen",
  dateOfSecondMeeting: "2026-09-04",
  requestedDocuments: emptyDocs().map((d, i) => ({
    ...d,
    received: i < 6,
  })),
  referredBy: "Existing client — David Chen",
  familyNotes:
    "Second marriage, 18 years. Both want to stay in the home as long as health allows. Close with Marguerite’s sister in San Diego. Gerry still mentors two former colleagues.",
  client: {
    ...emptyPerson(),
    firstName: "Germain",
    nickname: "Gerry",
    lastName: "Hammarth",
    dob: "1958-04-12",
    maritalStatus: "Married",
    yearsMarried: "18",
    jobTitle: "Retired VP, Operations",
    employer: "Pacific Industrial (last)",
    yearsAtJob: "27",
    retirementAge: "64",
  },
  spouse: {
    ...emptyPerson(),
    firstName: "Marguerite",
    nickname: "Marge",
    lastName: "Bonous-Hammarth",
    dob: "1960-09-03",
    maritalStatus: "Married",
    yearsMarried: "18",
    jobTitle: "Retired Curriculum Director",
    employer: "Capistrano Unified (last)",
    yearsAtJob: "22",
    retirementAge: "63",
  },
  address: {
    street: "27 Driftwood Lane",
    city: "Laguna Niguel",
    state: "CA",
    zip: "92677",
    country: "USA",
  },
  children: [
    { id: uid(), name: "Daniel Hammarth", age: "41" },
    { id: uid(), name: "Claire Hammarth-Reed", age: "38" },
    { id: uid(), name: "Sophie Bonous", age: "34" },
  ],
  grandchildrenCount: "5",
  grandchildrenNotes: "Ages 3–14. 529s are under the parents; grandparents want to fund education gifts without complicating titling.",
  advisors: {
    other: { ...emptyAdvisor(), name: "", firm: "", notes: "" },
    attorney: {
      name: "Patricia Lang",
      firm: "Lang & Whitfield LLP",
      notes: "Trust drafted 2017. Not reviewed since move.",
      preference: true,
      commitment: false,
    },
    accountant: {
      name: "Evan Cho, CPA",
      firm: "Cho Tax Group",
      notes: "Prepares return. No multi-year tax map.",
      preference: false,
      commitment: true,
    },
    insurance: {
      name: "Robert Hale",
      firm: "Hale Independent",
      notes: "Home/auto only. No umbrella on file.",
      preference: false,
      commitment: false,
    },
  },
  realEstate: [
    {
      id: uid(),
      description: "Primary residence — Laguna Niguel",
      marketValue: 2_150_000,
      liabilityAmount: 0,
      rateTerm: "Paid off 2023",
      payment: 0,
      incomeEbt: 0,
      acquisitionYear: "2004",
      purchasePrice: 875_000,
      additions: 210_000,
      ownership: "Trust",
    },
    {
      id: uid(),
      description: "Palm Desert condo (personal use)",
      marketValue: 640_000,
      liabilityAmount: 0,
      rateTerm: "",
      payment: 0,
      incomeEbt: 0,
      acquisitionYear: "2016",
      purchasePrice: 410_000,
      additions: 45_000,
      ownership: "Joint / community",
    },
  ],
  deferred: [
    {
      id: uid(),
      custodian: "Fidelity Traditional IRA",
      marketValue: 1_842_000,
      additions: 0,
      extra: 0,
      extraLabel: "Company match",
      type: "Traditional IRA",
      ownership: "Gerry",
      beneficiary: "Marguerite (primary); children per stirpes",
      feePct: 0.17,
    },
    {
      id: uid(),
      custodian: "Schwab Rollover IRA",
      marketValue: 1_120_000,
      additions: 0,
      extra: 0,
      extraLabel: "Company match",
      type: "Rollover IRA",
      ownership: "Marguerite",
      beneficiary: "Gerry (primary); children per stirpes",
      feePct: 0.17,
    },
    {
      id: uid(),
      custodian: "Fidelity 401(k) — Pacific Industrial",
      marketValue: 422_000,
      additions: 0,
      extra: 0,
      extraLabel: "Company match",
      type: "401(k)",
      ownership: "Gerry",
      beneficiary: "Marguerite",
      feePct: 0.17,
    },
  ],
  roth: [],
  investments: [
    {
      id: uid(),
      custodian: "Schwab Brokerage (Joint)",
      marketValue: 1_875_000,
      additions: 0,
      extra: 1_140_000,
      extraLabel: "Cost basis",
      type: "Brokerage / ETF",
      ownership: "Joint",
      beneficiary: "TOD — children equal",
      feePct: 0.17,
    },
    {
      id: uid(),
      custodian: "Fidelity Individual",
      marketValue: 560_000,
      additions: 0,
      extra: 318_000,
      extraLabel: "Cost basis",
      type: "Individual stocks / funds",
      ownership: "Gerry",
      beneficiary: "Marguerite",
      feePct: 0.17,
    },
    {
      id: uid(),
      custodian: "Coinbase",
      marketValue: 200_000,
      additions: 0,
      extra: 74_000,
      extraLabel: "Cost basis",
      type: "Crypto",
      ownership: "Gerry",
      beneficiary: "",
      feePct: 0,
    },
  ],
  cash: [
    {
      id: uid(),
      description: "Schwab Investor Checking",
      marketValue: 185_000,
      intRate: "0.45%",
      owner: "Joint",
    },
    {
      id: uid(),
      description: "Fidelity CMA",
      marketValue: 415_000,
      intRate: "4.6%",
      owner: "Joint",
    },
    {
      id: uid(),
      description: "Brokered CDs / T-bills ladder",
      marketValue: 700_000,
      intRate: "4.8%",
      owner: "Joint",
    },
  ],
  business: [],
  otherLiabilities: [],
  insurance: [
    {
      id: uid(),
      company: "Northwestern Mutual",
      type: "Term life (expires 2028)",
      deathBenefit: 500_000,
      insured: "Gerry",
      owner: "Gerry",
      policyDate: "2013-06-01",
      annualPremium: 2_840,
      cashValue: 0,
      beneficiary: "Marguerite",
    },
    {
      id: uid(),
      company: "State Farm",
      type: "Homeowners / auto",
      deathBenefit: 0,
      insured: "Both",
      owner: "Joint",
      policyDate: "2004-01-01",
      annualPremium: 6_200,
      cashValue: 0,
      beneficiary: "",
    },
  ],
  income: [
    {
      id: uid(),
      description: "Pacific Industrial pension",
      currentAmount: 120_000,
      futureRetirementAmount: 120_000,
      type: "Pension",
      startDate: "2022-07-01",
      owner: "Gerry",
      survivorCola: "50% joint & survivor, no COLA",
    },
    {
      id: uid(),
      description: "CalSTRS pension",
      currentAmount: 52_000,
      futureRetirementAmount: 52_000,
      type: "Pension",
      startDate: "2023-09-01",
      owner: "Marguerite",
      survivorCola: "Beneficiary option, 2% COLA",
    },
    {
      id: uid(),
      description: "Social Security — Gerry",
      currentAmount: 52_000,
      futureRetirementAmount: 52_000,
      type: "Social Security",
      startDate: "2025-04-01",
      owner: "Gerry",
      survivorCola: "COLA",
    },
    {
      id: uid(),
      description: "Social Security — Marguerite",
      currentAmount: 37_500,
      futureRetirementAmount: 37_500,
      type: "Social Security",
      startDate: "2026-01-01",
      owner: "Marguerite",
      survivorCola: "COLA",
    },
  ],
  annualExpenses: 288_000,
  filingStatus: "Married Filing Jointly",
  capLossCarryForward: 18_400,
  taxableIncome: 214_000,
  itemizedDed: 42_800,
  federalTax: 38_600,
  stateTax: 14_200,
  ficaTax: 0,
  taxDeferredContributions: 0,
  retirementBenefits:
    "Gerry: 50% J&S on industrial pension, no COLA. Marguerite: CalSTRS with 2% COLA. Both claiming Social Security.",
  goals:
    "Stay in Laguna Niguel. Keep the desert condo for family weeks. Gift $50k/year toward grandchildren education without creating estate-tax issues. Travel 6–8 weeks a year. Leave the bulk of the estate to the three children equally, with a donor-advised fund funded over the next decade.",
  concerns:
    "Sequence of returns in the first decade of retirement. California income tax. What happens to the pension if Gerry dies first. Crypto is concentrated and untitled. Trust has not been reviewed since 2017. No umbrella, no LTC. Roth conversions were never started.",
  estateDocs: {
    will: true,
    trust: true,
    financialPoa: true,
    medicalPoa: false,
    hipaa: false,
    qualityOfLife: false,
  },
  hasUmbrella: false,
  hasLtc: false,
  sectionNotes: {
    opening: "Documents still out: estate restatement, LTC illustration, umbrella quote.",
    cash: "Cash is high by design after 2022 — they want a two-year spending reserve before we invest the excess.",
    roth: "Confirmed: no Roth IRAs, no backdoor history.",
  },
  completedSections: [
    "opening",
    "family",
    "occupation",
    "advisors",
    "real-estate",
    "deferred",
    "roth",
    "investments",
    "cash",
    "business",
    "liabilities",
    "insurance",
    "income",
    "goals",
  ],
};

export const HAMMARTH_NAME = "Hammarth, Germain & Marguerite";

/** Stable per-user id so the sample file survives a database reset. */
export function hammarthHouseholdId(userId: string) {
  return `hammarth-${userId}`;
}
