/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoAssessmentRouteImport } from './routes/demo.assessment'
import { Route as HouseholdsIdRouteImport } from './routes/households.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as HouseholdsIdIndexRouteImport } from './routes/households.$id.index'
import { Route as HouseholdsIdAssessmentRouteImport } from './routes/households.$id.assessment'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAssessmentRoute = DemoAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => DemoRoute,
} as any)
const HouseholdsIdRoute = HouseholdsIdRouteImport.update({
  id: '/households/$id',
  path: '/households/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsIdIndexRoute = HouseholdsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HouseholdsIdRoute,
} as any)
const HouseholdsIdAssessmentRoute = HouseholdsIdAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => HouseholdsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/demo/assessment': typeof DemoAssessmentRoute
  '/households/$id': typeof HouseholdsIdRouteWithChildren
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/households/$id/assessment': typeof HouseholdsIdAssessmentRoute
  '/households/$id/': typeof HouseholdsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/demo/assessment': typeof DemoAssessmentRoute
  '/demo': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/households/$id/assessment': typeof HouseholdsIdAssessmentRoute
  '/households/$id': typeof HouseholdsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/demo/assessment': typeof DemoAssessmentRoute
  '/households/$id': typeof HouseholdsIdRouteWithChildren
  '/demo/': typeof DemoIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/households/$id/assessment': typeof HouseholdsIdAssessmentRoute
  '/households/$id/': typeof HouseholdsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/demo/assessment'
    | '/households/$id'
    | '/demo/'
    | '/api/auth/$'
    | '/households/$id/assessment'
    | '/households/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/demo/assessment'
    | '/demo'
    | '/api/auth/$'
    | '/households/$id/assessment'
    | '/households/$id'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/demo/assessment'
    | '/households/$id'
    | '/demo/'
    | '/api/auth/$'
    | '/households/$id/assessment'
    | '/households/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  HouseholdsIdRoute: typeof HouseholdsIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/assessment': {
      id: '/demo/assessment'
      path: '/assessment'
      fullPath: '/demo/assessment'
      preLoaderRoute: typeof DemoAssessmentRouteImport
      parentRoute: typeof DemoRoute
    }
    '/households/$id': {
      id: '/households/$id'
      path: '/households/$id'
      fullPath: '/households/$id'
      preLoaderRoute: typeof HouseholdsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households/$id/': {
      id: '/households/$id/'
      path: '/'
      fullPath: '/households/$id/'
      preLoaderRoute: typeof HouseholdsIdIndexRouteImport
      parentRoute: typeof HouseholdsIdRoute
    }
    '/households/$id/assessment': {
      id: '/households/$id/assessment'
      path: '/assessment'
      fullPath: '/households/$id/assessment'
      preLoaderRoute: typeof HouseholdsIdAssessmentRouteImport
      parentRoute: typeof HouseholdsIdRoute
    }
  }
}

interface DemoRouteChildren {
  DemoAssessmentRoute: typeof DemoAssessmentRoute
  DemoIndexRoute: typeof DemoIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAssessmentRoute: DemoAssessmentRoute,
  DemoIndexRoute: DemoIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

interface HouseholdsIdRouteChildren {
  HouseholdsIdAssessmentRoute: typeof HouseholdsIdAssessmentRoute
  HouseholdsIdIndexRoute: typeof HouseholdsIdIndexRoute
}

const HouseholdsIdRouteChildren: HouseholdsIdRouteChildren = {
  HouseholdsIdAssessmentRoute: HouseholdsIdAssessmentRoute,
  HouseholdsIdIndexRoute: HouseholdsIdIndexRoute,
}

const HouseholdsIdRouteWithChildren = HouseholdsIdRoute._addFileChildren(
  HouseholdsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  HouseholdsIdRoute: HouseholdsIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
